name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build -t node_docker_dictionary .
    - name: Tags
      run: |
        docker tag node_docker_dictionary ${{ secrets.DOCKER_USER }}/node_docker_dictionary:${{ github.sha }}
        docker tag node_docker_dictionary ${{ secrets.DOCKER_USER }}/node_docker_dictionary:latest
    - name: Docker Push
      run: |
        docker push ${{ secrets.DOCKER_USER }}/node_docker_dictionary:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/node_docker_dictionary:latest
